#!/usr/bin/env sh
set -eu

APP_URL="${APP_URL:-http://localhost:3000}"
ENV_FILE="${ENV_FILE:-.env}"
LOG_DIR="${LOG_DIR:-$(pwd)/logs/cron}"

MARKER_BEGIN="# BEGIN TaskTracker managed cron"
MARKER_END="# END TaskTracker managed cron"
CRON_SECRET_PLACEHOLDER="change-me-to-a-random-string"

read_env_value() {
    key="$1"
    awk -v key="$key" '
        $0 ~ "^[[:space:]]*" key "=" {
            sub("^[[:space:]]*" key "=", "")
            gsub(/^[[:space:]]+|[[:space:]]+$/, "")
            gsub(/^"|"$/, "")
            gsub(/^'\''|'\''$/, "")
            print
            exit
        }
    ' "$ENV_FILE"
}

shell_quote() {
    value="$1"
    printf "'%s'" "$(printf "%s" "$value" | sed "s/'/'\\\\''/g")"
}

curl_with_retries() {
    description="$1"
    shift
    attempt=1
    max_attempts=12

    while [ "$attempt" -le "$max_attempts" ]; do
        if curl "$@"; then
            return 0
        fi

        echo "Waiting for $description... attempt $attempt/$max_attempts" >&2
        attempt=$((attempt + 1))
        sleep 5
    done

    echo "ERROR: $description did not respond after $max_attempts attempts." >&2
    return 1
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "ERROR: required command '$1' is not installed." >&2
        exit 1
    fi
}

require_command awk
require_command crontab
require_command curl
require_command mktemp
require_command sed
require_command sleep

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: $ENV_FILE was not found. Cannot configure cron without CRON_SECRET." >&2
    exit 1
fi

CRON_SECRET="${CRON_SECRET:-$(read_env_value CRON_SECRET || true)}"
if [ -z "$CRON_SECRET" ] || [ "$CRON_SECRET" = "$CRON_SECRET_PLACEHOLDER" ]; then
    echo "ERROR: CRON_SECRET is empty or still uses the placeholder value." >&2
    exit 1
fi

mkdir -p "$LOG_DIR"

auth_header="$(shell_quote "Authorization: Bearer $CRON_SECRET")"
recurrence_url="$(shell_quote "$APP_URL/api/cron/recurrence")"
cleanup_url="$(shell_quote "$APP_URL/api/cron/cleanup")"
recurrence_log="$(shell_quote "$LOG_DIR/recurrence.log")"
cleanup_log="$(shell_quote "$LOG_DIR/cleanup.log")"

tmp_current="$(mktemp)"
tmp_next="$(mktemp)"
trap 'rm -f "$tmp_current" "$tmp_next"' EXIT

crontab -l 2>/dev/null > "$tmp_current" || true

awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" '
    $0 == begin { skip = 1; next }
    $0 == end { skip = 0; next }
    skip != 1 { print }
' "$tmp_current" > "$tmp_next"

{
    printf "\n%s\n" "$MARKER_BEGIN"
    printf "# Generated by scripts/setup-cron.sh. Safe to rerun on every deploy.\n"
    printf "*/5 * * * * curl -fsS --max-time 30 -X POST %s -H %s >> %s 2>&1\n" "$recurrence_url" "$auth_header" "$recurrence_log"
    printf "0 3 * * 0 curl -fsS --max-time 60 -X POST %s -H %s >> %s 2>&1\n" "$cleanup_url" "$auth_header" "$cleanup_log"
    printf "%s\n" "$MARKER_END"
} >> "$tmp_next"

crontab "$tmp_next"

if ! crontab -l | grep -F "$MARKER_BEGIN" >/dev/null; then
    echo "ERROR: managed cron block was not installed." >&2
    exit 1
fi

if ! crontab -l | grep -F "/api/cron/recurrence" >/dev/null; then
    echo "ERROR: recurrence cron entry is missing after installation." >&2
    exit 1
fi

echo "Cron entries installed:"
crontab -l | sed -n "/$MARKER_BEGIN/,/$MARKER_END/p"

echo "Checking cron endpoint auth..."
curl_with_retries "cron endpoint auth" -fsS --max-time 30 "$APP_URL/api/cron/recurrence" -H "Authorization: Bearer $CRON_SECRET" >/dev/null

echo "Running recurrence generation once after deploy..."
curl_with_retries "recurrence generation" -fsS --max-time 60 -X POST "$APP_URL/api/cron/recurrence" -H "Authorization: Bearer $CRON_SECRET" >/dev/null

echo "Cron setup completed."
